import { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { BarChart3, Check, Clock3, FolderOpen, Maximize2, Minimize2, Pause, Pin, PinOff, Play, Plus, Settings, Sparkles, Trash2, X } from "lucide-react";
import "./styles.css";
import corgiEat1 from "./assets/corgi-eat-1.png";
import corgiEat2 from "./assets/corgi-eat-2.png";
import corgiEat3 from "./assets/corgi-eat-3.png";
import corgiEat4 from "./assets/corgi-eat-4.png";
import corgiPlay1 from "./assets/corgi-play-1.png";
import corgiPlay2 from "./assets/corgi-play-2.png";
import corgiPlay3 from "./assets/corgi-play-3.png";
import corgiPlay4 from "./assets/corgi-play-4.png";
import corgiSleep1 from "./assets/corgi-sleep-1.png";
import corgiSleep2 from "./assets/corgi-sleep-2.png";
import corgiSleep3 from "./assets/corgi-sleep-3.png";
import corgiSleep4 from "./assets/corgi-sleep-4.png";

type ActiveTimer = { task: Task; startedAt: string; pausedSeconds: number; pausedAt?: string };
type DogRewardKind = "food" | "freezeDried" | "snack" | "toy" | "skill" | "walk" | "care";
type DogReward = { categoryId: string; item: string; action: string; message: string; animation: "sniff" | "eat" | "learn" | "walk" | "play" | "care"; stat: "fullness" | "happiness" | "bond" | "skillPoints" | "social" | "care"; amount: number };
type DayMetric = { date: string; tasks: CompletedTask[]; totalSeconds: number; overtimeSeconds: number; score: number };
const defaultPrefs: Record<string, DogRewardKind> = { research: "freezeDried", writing: "food", development: "skill", meeting: "walk", leisure: "toy", misc: "care" };
const rewardOptions: Record<DogRewardKind, Omit<DogReward, "categoryId">> = {
  food: { item: "狗粮", action: "埋头吃饭，饱腹感上升", message: "任务完成，小狗吃到一碗狗粮。", animation: "eat", stat: "fullness", amount: 10 },
  freezeDried: { item: "冻干", action: "认真嗅嗅然后开心吃掉", message: "任务完成，小狗获得一块冻干。", animation: "sniff", stat: "happiness", amount: 6 },
  snack: { item: "零食", action: "开心摇尾巴，亲密感上升", message: "任务完成，小狗获得一份零食。", animation: "eat", stat: "bond", amount: 6 },
  toy: { item: "玩具", action: "追着球玩了一会儿", message: "任务完成，小狗获得一个玩具。", animation: "play", stat: "happiness", amount: 10 },
  skill: { item: "技能训练", action: "练习新动作，技能进度 +1", message: "任务完成，小狗学到一点新技能。", animation: "learn", stat: "skillPoints", amount: 1 },
  walk: { item: "散步机会", action: "出门转一圈，社交值上升", message: "任务完成，小狗获得一次散步。", animation: "walk", stat: "social", amount: 8 },
  care: { item: "护理", action: "毛毛变蓬松，舒服值上升", message: "任务完成，小狗获得一次清洁护理。", animation: "care", stat: "care", amount: 10 }
};
const uid = () => crypto.randomUUID();
const todayKey = () => new Date().toISOString().slice(0, 10);
const clamp = (n: number) => Math.max(0, Math.min(100, Math.round(n)));
const fmt = (sec: number) => { const v = Math.abs(sec), h = Math.floor(v / 3600), m = Math.floor((v % 3600) / 60), s = v % 60; return `${sec < 0 ? "-" : ""}${h ? `${String(h).padStart(2, "0")}:` : ""}${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")}`; };
const mins = (sec: number) => `${Math.round(sec / 60)} 分钟`;
const time = (iso: string) => new Intl.DateTimeFormat("zh-CN", { hour: "2-digit", minute: "2-digit" }).format(new Date(iso));
const rewardKind = (prefs: AppSettings["dogRewardPreferences"] | undefined, id: string): DogRewardKind => prefs?.[id] ?? defaultPrefs[id] ?? "snack";
const rewardFor = (id: string, prefs?: AppSettings["dogRewardPreferences"]): DogReward => ({ categoryId: id, ...rewardOptions[rewardKind(prefs, id)] });
const cleanReview = (s: string) => s.replace(/\*\*/g, "").replace(/^#+\s*/gm, "").replace(/^\s*[-*]\s+/gm, "• ").trim();
function normalize(d: AppData): AppData { return { ...d, settings: { ...d.settings, alwaysOnTop: d.settings.alwaysOnTop ?? true, dogRewardPreferences: { ...defaultPrefs, ...(d.settings.dogRewardPreferences ?? {}) } }, dog: { name: d.dog?.name ?? "Todo", gender: d.dog?.gender ?? "未设定", birthday: d.dog?.birthday ?? new Date().toISOString(), enabled: d.dog?.enabled ?? true, fullness: d.dog?.fullness ?? 40, happiness: d.dog?.happiness ?? 50, bond: d.dog?.bond ?? 20, skillPoints: d.dog?.skillPoints ?? 0, social: d.dog?.social ?? 10, care: d.dog?.care ?? 50 }, quickTasks: d.quickTasks?.length ? d.quickTasks : [{ id: "break-5", title: "休息", estimateMinutes: 5, categoryId: "leisure" }] }; }
function dayMetrics(tasks: CompletedTask[]) { const g: Record<string, CompletedTask[]> = {}; tasks.forEach(t => { const k = t.completedAt.slice(0, 10); g[k] = [...(g[k] ?? []), t]; }); return Object.fromEntries(Object.entries(g).map(([date, ts]) => { const totalSeconds = ts.reduce((s, t) => s + t.actualSeconds, 0), overtimeSeconds = ts.reduce((s, t) => s + t.overtimeSeconds, 0); return [date, { date, tasks: ts, totalSeconds, overtimeSeconds, score: Math.max(0, Math.round(Math.min(64, totalSeconds / 225) + Math.min(24, ts.length * 6) - (totalSeconds ? Math.min(28, overtimeSeconds / totalSeconds * 36) : 0))) }]; })) as Record<string, DayMetric>; }

function App() {
  const [data, setData] = useState<AppData | null>(null), [mode, setMode] = useState<"compact" | "expanded">("compact"), [active, setActive] = useState<ActiveTimer | null>(null), [now, setNow] = useState(Date.now());
  const [title, setTitle] = useState(""), [minutes, setMinutes] = useState(45), [cat, setCat] = useState("research"), [note, setNote] = useState(""), [newCat, setNewCat] = useState("");
  const [musings, setMusings] = useState<TaskMusing[]>([]), [musing, setMusing] = useState(""), [doneNote, setDoneNote] = useState(""), [doneOpen, setDoneOpen] = useState(false), [interruptNote, setInterruptNote] = useState(""), [interruptOpen, setInterruptOpen] = useState(false);
  const [quickTitle, setQuickTitle] = useState(""), [quickMinutes, setQuickMinutes] = useState(5), [review, setReview] = useState(""), [reviewError, setReviewError] = useState(""), [reviewLoading, setReviewLoading] = useState(false), [selectedDate, setSelectedDate] = useState(todayKey()), [pinned, setPinned] = useState(true), [dogReward, setDogReward] = useState<DogReward | null>(null);
  useEffect(() => { void window.floatodo.loadData().then(x => { const n = normalize(x); setData(n); setPinned(n.settings.alwaysOnTop); setCat(n.categories[0]?.id ?? "research"); void window.floatodo.setAlwaysOnTop(n.settings.alwaysOnTop); }); }, []);
  useEffect(() => { const t = window.setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(t); }, []);
  useEffect(() => { void window.floatodo.sendDogState({ idle: !active || active.task.categoryId === "leisure" ? "toy" : "sleep" }); }, [active?.task.categoryId]);
  const save = (fn: (d: AppData) => AppData) => setData(d => { if (!d) return d; const n = fn(d); void window.floatodo.saveData(n); return n; });
  const cats = useMemo(() => new Map(data?.categories.map(c => [c.id, c]) ?? []), [data]);
  const elapsed = active ? Math.max(0, Math.floor(((active.pausedAt ? new Date(active.pausedAt).getTime() : now) - new Date(active.startedAt).getTime()) / 1000) - active.pausedSeconds) : 0;
  const remaining = active ? active.task.estimateMinutes * 60 - elapsed : 0, overtime = Boolean(active && remaining < 0);
  const tuckPayload = { title: active?.task.title ?? "Floatodo", time: active ? fmt(overtime ? elapsed - active.task.estimateMinutes * 60 : remaining) : "00:00", overtime };
  const today = data?.completedTasks.filter(t => t.completedAt.slice(0, 10) === todayKey()) ?? [], metrics = dayMetrics(data?.completedTasks ?? []), dates = Array.from(new Set(data?.completedTasks.map(t => t.completedAt.slice(0, 10)))).sort().reverse(), selected = data?.completedTasks.filter(t => t.completedAt.slice(0, 10) === selectedDate) ?? [];
  useEffect(() => { void window.floatodo.updateTuckWindow(tuckPayload); }, [tuckPayload.title, tuckPayload.time, tuckPayload.overtime]);
  const switchMode = async (m: "compact" | "expanded") => { setMode(m); m === "compact" ? await window.floatodo.compactWindow() : await window.floatodo.expandWindow(); };
  const togglePin = async () => { if (!data) return; const ok = await window.floatodo.setAlwaysOnTop(!pinned); setPinned(ok); save(d => ({ ...d, settings: { ...d.settings, alwaysOnTop: ok } })); };
  const addTask = () => { if (!data || !title.trim()) return; const task: Task = { id: uid(), title: title.trim(), categoryId: cat, estimateMinutes: Math.max(1, minutes), note: note.trim() || undefined, createdAt: new Date().toISOString() }; save(d => ({ ...d, tasks: [task, ...d.tasks] })); setTitle(""); setNote(""); };
  const addCategory = () => { if (!data || !newCat.trim()) return; const colors = ["#2563eb", "#14b8a6", "#8b5cf6", "#f59e0b", "#ef4444", "#64748b"], c = { id: uid(), name: newCat.trim(), color: colors[data.categories.length % colors.length] }; save(d => ({ ...d, categories: [...d.categories, c], settings: { ...d.settings, dogRewardPreferences: { ...(d.settings.dogRewardPreferences ?? {}), [c.id]: "snack" } } })); setCat(c.id); setNewCat(""); };
  const start = (task: Task) => { if (active) return; setActive({ task, startedAt: new Date().toISOString(), pausedSeconds: 0 }); setMusings([]); setMusing(""); };
  const startQuick = (q: QuickTask) => start({ id: uid(), title: q.title, estimateMinutes: q.estimateMinutes, categoryId: q.categoryId, createdAt: new Date().toISOString() });
  const addQuick = () => { if (!quickTitle.trim()) return; save(d => ({ ...d, quickTasks: [...d.quickTasks, { id: uid(), title: quickTitle.trim(), estimateMinutes: Math.max(1, quickMinutes), categoryId: "misc" }] })); setQuickTitle(""); setQuickMinutes(5); };
  const pause = () => { if (!active) return; active.pausedAt ? setActive({ ...active, pausedAt: undefined, pausedSeconds: active.pausedSeconds + Math.max(0, Math.floor((Date.now() - new Date(active.pausedAt).getTime()) / 1000)) }) : setActive({ ...active, pausedAt: new Date().toISOString() }); };
  const sendMusing = () => { const text = musing.trim(); if (!text) return; setMusings(a => [...a, { id: uid(), text, createdAt: new Date().toISOString() }]); setMusing(""); };
  const openDone = () => { if (!active) return; setDoneOpen(true); if (!active.pausedAt) setActive({ ...active, pausedAt: new Date().toISOString() }); };
  const boostDog = (dog: DogProfile, r: DogReward) => { const d = { ...dog, bond: clamp(dog.bond + 4) }; if (r.stat === "skillPoints") d.skillPoints += r.amount; if (r.stat === "fullness") d.fullness = clamp(d.fullness + r.amount); if (r.stat === "happiness") d.happiness = clamp(d.happiness + r.amount); if (r.stat === "bond") d.bond = clamp(d.bond + r.amount); if (r.stat === "social") d.social = clamp(d.social + r.amount); if (r.stat === "care") d.care = clamp(d.care + r.amount); return d; };
  const complete = () => { if (!active || !data) return; const done: CompletedTask = { ...active.task, startedAt: active.startedAt, completedAt: new Date().toISOString(), actualSeconds: Math.max(1, elapsed), overtimeSeconds: Math.max(0, elapsed - active.task.estimateMinutes * 60), status: "completed", musings: musings.length ? musings : undefined, reflection: doneNote.trim() || undefined }; const r = rewardFor(active.task.categoryId, data.settings.dogRewardPreferences); save(d => ({ ...d, dog: d.dog.enabled ? boostDog(d.dog, r) : d.dog, tasks: d.tasks.filter(t => t.id !== active.task.id), completedTasks: [done, ...d.completedTasks] })); if (data.dog.enabled) { setDogReward(r); void window.floatodo.sendDogReward(r); window.setTimeout(() => setDogReward(null), 4200); } setActive(null); setMusings([]); setDoneNote(""); setDoneOpen(false); };
  const openInterrupt = () => { if (!active) return; setInterruptOpen(true); if (!active.pausedAt) setActive({ ...active, pausedAt: new Date().toISOString() }); };
  const interrupt = () => { if (!active) return; const actualSeconds = Math.max(1, elapsed), spentMinutes = Math.max(1, Math.ceil(actualSeconds / 60)), remainingEstimateMinutes = Math.max(1, active.task.estimateMinutes - spentMinutes); const reason = interruptNote.trim() || "任务中断"; const interrupted: CompletedTask = { ...active.task, startedAt: active.startedAt, completedAt: new Date().toISOString(), actualSeconds, overtimeSeconds: 0, status: "interrupted", remainingEstimateMinutes, musings: musings.length ? musings : undefined, reflection: reason }; save(d => ({ ...d, tasks: d.tasks.map(t => t.id === active.task.id ? { ...t, estimateMinutes: remainingEstimateMinutes } : t), completedTasks: [interrupted, ...d.completedTasks] })); setActive(null); setMusings([]); setMusing(""); setDoneNote(""); setDoneOpen(false); setInterruptNote(""); setInterruptOpen(false); };
  const genReview = async () => { if (!data) return; setReview(""); setReviewError(""); if (!data.settings.deepseekApiKey.trim()) return setReviewError("请先在设置里填写 DeepSeek API Key。"); if (!today.length) return setReviewError("今天还没有任务记录。"); setReviewLoading(true); try { const lines = today.map(t => `- ${t.title}｜${t.status === "interrupted" ? "中断" : "完成"}｜${cats.get(t.categoryId)?.name ?? "未分类"}｜预估 ${t.estimateMinutes} 分钟｜实际 ${mins(t.actualSeconds)}${t.status === "interrupted" ? `｜剩余预估 ${t.remainingEstimateMinutes ?? t.estimateMinutes} 分钟` : `｜超时 ${mins(t.overtimeSeconds)}`}｜备注 ${t.reflection ?? "无"}`); const text = await window.floatodo.requestDeepSeekReview({ apiKey: data.settings.deepseekApiKey, model: data.settings.deepseekModel, prompt: `请用简洁中文复盘今天的任务，不要使用 Markdown 加粗，400 字以内。\n${lines.join("\n")}` }); setReview(cleanReview(text)); } catch (e) { setReviewError(e instanceof Error ? e.message : "生成失败"); } finally { setReviewLoading(false); } };
  if (!data) return <main className="app-shell compact"><p className="empty">正在打开 Floatodo...</p></main>;
  return <main className={`app-shell ${mode}`}><header className="titlebar"><div><strong>Floatodo</strong><span>{mode === "compact" ? "悬浮计时" : "任务工作台"}</span></div><div className="window-actions"><button onClick={togglePin}>{pinned ? <Pin size={16} /> : <PinOff size={16} />}</button><button onClick={() => void switchMode(mode === "compact" ? "expanded" : "compact")}>{mode === "compact" ? <Maximize2 size={16} /> : <Minimize2 size={16} />}</button><button onClick={() => void window.floatodo.minimizeWindow()}><Minimize2 size={16} /></button><button onClick={() => void window.floatodo.closeWindow()}><X size={16} /></button></div></header>{mode === "compact" ? <Compact active={active} remaining={remaining} elapsed={elapsed} overtime={overtime} next={data.tasks[0]} quick={data.quickTasks} cats={cats} startNext={() => data.tasks[0] && start(data.tasks[0])} startQuick={startQuick} pause={pause} interrupt={openInterrupt} complete={openDone} musings={musings} musing={musing} setMusing={setMusing} sendMusing={sendMusing} quickTitle={quickTitle} quickMinutes={quickMinutes} setQuickTitle={setQuickTitle} setQuickMinutes={setQuickMinutes} addQuick={addQuick} /> : <Expanded data={data} active={active} remaining={remaining} elapsed={elapsed} overtime={overtime} cats={cats} title={title} setTitle={setTitle} minutes={minutes} setMinutes={setMinutes} cat={cat} setCat={setCat} note={note} setNote={setNote} newCat={newCat} setNewCat={setNewCat} addTask={addTask} addCategory={addCategory} deleteTask={id => save(d => ({ ...d, tasks: d.tasks.filter(t => t.id !== id) }))} start={start} complete={openDone} interrupt={openInterrupt} pause={pause} today={today} selected={selected} metrics={metrics} dates={dates} selectedDate={selectedDate} setSelectedDate={setSelectedDate} settings={data.settings} saveSettings={settings => save(d => ({ ...d, settings }))} genReview={genReview} review={review} reviewError={reviewError} reviewLoading={reviewLoading} dogReward={dogReward} updateDog={dog => save(d => ({ ...d, dog }))} />}{doneOpen && active && <Completion note={doneNote} setNote={setDoneNote} cancel={() => setDoneOpen(false)} confirm={complete} />}{interruptOpen && active && <InterruptDialog note={interruptNote} setNote={setInterruptNote} cancel={() => setInterruptOpen(false)} confirm={interrupt} />}</main>;
}

function Compact(p: { active: ActiveTimer | null; remaining: number; elapsed: number; overtime: boolean; next?: Task; quick: QuickTask[]; cats: Map<string, TaskCategory>; startNext: () => void; startQuick: (q: QuickTask) => void; pause: () => void; interrupt: () => void; complete: () => void; musings: TaskMusing[]; musing: string; setMusing: (v: string) => void; sendMusing: () => void; quickTitle: string; quickMinutes: number; setQuickTitle: (v: string) => void; setQuickMinutes: (v: number) => void; addQuick: () => void }) { const t = p.active?.task, c = t ? p.cats.get(t.categoryId) : undefined; return <section className="compact-view"><div className="timer-shell"><div className="timer-meta"><span>{t ? c?.name ?? "未分类" : "等待开始"}</span></div><strong className={p.overtime ? "overtime" : ""}>{t ? fmt(p.overtime ? p.elapsed - t.estimateMinutes * 60 : p.remaining) : "00:00"}</strong><p>{t ? t.title : p.next ? `下一项：${p.next.title}` : "先添加一个任务。"}</p>{t ? <div className="compact-controls compact-controls-three"><button onClick={p.pause}>{p.active?.pausedAt ? <Play size={17} /> : <Pause size={17} />}{p.active?.pausedAt ? "继续" : "暂停"}</button><button onClick={p.interrupt}>中断</button><button className="primary" onClick={p.complete}><Check size={17} />完成</button></div> : <button className="primary" onClick={p.startNext} disabled={!p.next}><Play size={17} />开始下一项</button>}</div>{t && <Musing musings={p.musings} value={p.musing} setValue={p.setMusing} send={p.sendMusing} />}<div className="quick-task-box"><div className="section-label">固定任务</div><div className="quick-task-list">{p.quick.map(q => <button key={q.id} disabled={Boolean(p.active)} onClick={() => p.startQuick(q)}>{q.title} · {q.estimateMinutes}m</button>)}</div><div className="quick-task-form"><input value={p.quickTitle} onChange={e => p.setQuickTitle(e.target.value)} placeholder="自定义固定任务" /><input type="number" min={1} value={p.quickMinutes} onChange={e => p.setQuickMinutes(Number(e.target.value))} /><button onClick={p.addQuick}>保存</button></div></div></section>; }
function Musing(p: { musings: TaskMusing[]; value: string; setValue: (v: string) => void; send: () => void }) { return <div className="musing-box"><div className="section-label">任务进行中碎碎念</div><div className="musing-list">{p.musings.length ? p.musings.map(x => <div key={x.id} className="musing-message"><span>{time(x.createdAt)}</span><p>{x.text}</p></div>) : <p className="empty">像聊天一样记录过程想法。</p>}</div><div className="musing-input-row"><textarea value={p.value} onChange={e => p.setValue(e.target.value)} placeholder="比如：好有意思呀 / 有点难了" /><button className="primary" onClick={p.send}>发送</button></div></div>; }
function Expanded(p: { data: AppData; active: ActiveTimer | null; remaining: number; elapsed: number; overtime: boolean; cats: Map<string, TaskCategory>; title: string; setTitle: (v: string) => void; minutes: number; setMinutes: (v: number) => void; cat: string; setCat: (v: string) => void; note: string; setNote: (v: string) => void; newCat: string; setNewCat: (v: string) => void; addTask: () => void; addCategory: () => void; deleteTask: (id: string) => void; start: (t: Task) => void; complete: () => void; interrupt: () => void; pause: () => void; today: CompletedTask[]; selected: CompletedTask[]; metrics: Record<string, DayMetric>; dates: string[]; selectedDate: string; setSelectedDate: (v: string) => void; settings: AppSettings; saveSettings: (s: AppSettings) => void; genReview: () => void; review: string; reviewError: string; reviewLoading: boolean; dogReward: DogReward | null; updateDog: (d: DogProfile) => void }) { const [page, setPage] = useState<"focus" | "tasks" | "today" | "history" | "dog">("focus"); const tabs = [["focus", "计时", <Clock3 size={16} />], ["tasks", "任务", <Plus size={16} />], ["today", "今日", <BarChart3 size={16} />], ["history", "历史", <FolderOpen size={16} />], ["dog", "小狗", <span className="dog-tab-icon">C</span>]] as const; return <div className="expanded-workspace"><nav className="module-tabs">{tabs.map(t => <button key={t[0]} className={page === t[0] ? "active" : ""} onClick={() => setPage(t[0])}>{t[2]}{t[1]}</button>)}</nav><div className="module-page">{page === "focus" && <Focus active={p.active} remaining={p.remaining} elapsed={p.elapsed} overtime={p.overtime} complete={p.complete} interrupt={p.interrupt} pause={p.pause} />}{page === "tasks" && <Tasks {...p} />}{page === "today" && <Today completed={p.today} cats={p.cats} genReview={p.genReview} review={p.review} error={p.reviewError} loading={p.reviewLoading} />}{page === "history" && <History completed={p.selected} cats={p.cats} metrics={p.metrics} dates={p.dates} selectedDate={p.selectedDate} setSelectedDate={p.setSelectedDate} settings={p.settings} saveSettings={p.saveSettings} />}{page === "dog" && <DogPanel dog={p.data.dog} reward={p.dogReward} updateDog={p.updateDog} categories={p.data.categories} settings={p.settings} saveSettings={p.saveSettings} />}</div></div>; }
function Focus(p: { active: ActiveTimer | null; remaining: number; elapsed: number; overtime: boolean; complete: () => void; interrupt: () => void; pause: () => void }) { const t = p.active?.task; return <section className="focus-panel"><div className="section-label"><Clock3 size={17} />沉浸式计时</div><h1 className={p.overtime ? "overtime" : ""}>{t ? fmt(p.overtime ? p.elapsed - t.estimateMinutes * 60 : p.remaining) : "00:00"}</h1><p>{t ? t.title : "当前没有正在计时的任务"}</p>{t && <span className="pill">{p.overtime ? "已超时，正在正计时" : `预估 ${t.estimateMinutes} 分钟`}</span>}{t ? <div className="complete-box"><button onClick={p.pause}>{p.active?.pausedAt ? <Play size={17} /> : <Pause size={17} />}{p.active?.pausedAt ? "继续" : "暂停"}</button><button onClick={p.interrupt}>中断任务</button><button className="primary" onClick={p.complete}><Check size={17} />完成任务</button></div> : <p className="muted">从任务页选择一项开始。</p>}</section>; }
function Tasks(p: Parameters<typeof Expanded>[0]) { return <section className="task-panel"><div className="section-label"><Plus size={17} />增减任务</div><div className="form-row"><input value={p.title} onChange={e => p.setTitle(e.target.value)} placeholder="任务名称" /><input type="number" min={1} value={p.minutes} onChange={e => p.setMinutes(Number(e.target.value))} /></div><div className="form-row"><select value={p.cat} onChange={e => p.setCat(e.target.value)}>{p.data.categories.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select><button className="primary" onClick={p.addTask}><Plus size={17} />添加</button></div><input value={p.note} onChange={e => p.setNote(e.target.value)} placeholder="备注，可不填" /><div className="form-row"><input value={p.newCat} onChange={e => p.setNewCat(e.target.value)} placeholder="新增任务类型" /><button onClick={p.addCategory}>添加类型</button></div><div className="task-list">{p.data.tasks.map(t => { const c = p.cats.get(t.categoryId); return <article key={t.id} className="task-item"><div><strong>{t.title}</strong><span><i style={{ background: c?.color }} />{c?.name ?? "未分类"} · {t.estimateMinutes} 分钟</span></div><div className="item-actions"><button onClick={() => p.start(t)} disabled={Boolean(p.active)}><Play size={16} /></button><button onClick={() => p.deleteTask(t.id)} disabled={p.active?.task.id === t.id}><Trash2 size={16} /></button></div></article>; })}{!p.data.tasks.length && <p className="empty">任务列表是空的。</p>}</div></section>; }
function Today(p: { completed: CompletedTask[]; cats: Map<string, TaskCategory>; genReview: () => void; review: string; error: string; loading: boolean }) { return <section className="review-panel"><div className="section-label"><BarChart3 size={17} />今日工作回顾</div><Stats completed={p.completed} /><Charts completed={p.completed} cats={p.cats} /><List completed={p.completed} cats={p.cats} /><div className="ai-box"><button className="primary" onClick={p.genReview} disabled={p.loading}><Sparkles size={17} />{p.loading ? "生成中..." : "生成今日复盘"}</button>{p.error && <p className="error">{p.error}</p>}{p.review && <pre className="review-output">{p.review}</pre>}</div></section>; }
function History(p: { completed: CompletedTask[]; cats: Map<string, TaskCategory>; metrics: Record<string, DayMetric>; dates: string[]; selectedDate: string; setSelectedDate: (v: string) => void; settings: AppSettings; saveSettings: (s: AppSettings) => void }) { return <section className="history-panel"><div className="section-label"><FolderOpen size={17} />历史任务回顾</div><Calendar metrics={p.metrics} selectedDate={p.selectedDate} setSelectedDate={p.setSelectedDate} /><div className="date-tabs">{p.dates.map(d => <button key={d} className={d === p.selectedDate ? "active" : ""} onClick={() => p.setSelectedDate(d)}>{d}</button>)}</div><List completed={p.completed} cats={p.cats} /><SettingsPanel settings={p.settings} saveSettings={p.saveSettings} /></section>; }
function Stats(p: { completed: CompletedTask[] }) { const total = p.completed.reduce((s, t) => s + t.actualSeconds, 0), over = p.completed.reduce((s, t) => s + t.overtimeSeconds, 0); return <div className="stats-grid"><div><span>完成任务</span><strong>{p.completed.length}</strong></div><div><span>投入时间</span><strong>{mins(total)}</strong></div><div><span>超时时间</span><strong>{mins(over)}</strong></div></div>; }
function Charts(p: { completed: CompletedTask[]; cats: Map<string, TaskCategory> }) { const totals = p.completed.reduce<Record<string, number>>((a, t) => ({ ...a, [t.categoryId]: (a[t.categoryId] ?? 0) + t.actualSeconds }), {}), es = Object.entries(totals), max = Math.max(1, ...es.map(x => x[1])); return <div className="chart-grid"><div className="chart-card"><strong>时间分配</strong>{es.length ? es.map(([id, sec]) => { const c = p.cats.get(id); return <div className="bar-row" key={id}><span>{c?.name ?? "未分类"}</span><div className="bar-track"><i style={{ width: `${sec / max * 100}%`, background: c?.color ?? "#64748b" }} /></div><b>{mins(sec)}</b></div>; }) : <p className="empty">今天还没有数据。</p>}</div></div>; }
function Calendar(p: { metrics: Record<string, DayMetric>; selectedDate: string; setSelectedDate: (v: string) => void }) { const n = new Date(), start = new Date(n.getFullYear(), n.getMonth(), 1), len = new Date(n.getFullYear(), n.getMonth() + 1, 0).getDate(), blanks = Array.from({ length: start.getDay() }, (_, i) => i); return <div className="calendar-box"><div className="calendar-head"><strong>{n.getFullYear()} 年 {n.getMonth() + 1} 月</strong><span>颜色越深，工作量越高</span></div><div className="weekdays">{"日一二三四五六".split("").map(d => <span key={d}>{d}</span>)}</div><div className="calendar-grid">{blanks.map(i => <span key={i} />)}{Array.from({ length: len }, (_, i) => { const d = new Date(n.getFullYear(), n.getMonth(), i + 1), k = d.toISOString().slice(0, 10), m = p.metrics[k]; return <button key={k} className={`day-cell ${k === p.selectedDate ? "selected" : ""}`} style={{ "--score": m?.score ?? 0 } as React.CSSProperties} onClick={() => p.setSelectedDate(k)}><span>{i + 1}</span><i /></button>; })}</div></div>; }
function List(p: { completed: CompletedTask[]; cats: Map<string, TaskCategory> }) { if (!p.completed.length) return <p className="empty">还没有完成记录。</p>; return <div className="completed-list">{p.completed.map(t => <article key={`${t.id}-${t.completedAt}`} className="completed-item"><div><strong>{t.title}</strong><span>{p.cats.get(t.categoryId)?.name ?? "未分类"} · {time(t.completedAt)} · 实际 {mins(t.actualSeconds)}{t.status === "interrupted" ? ` · 剩余预估 ${t.remainingEstimateMinutes ?? t.estimateMinutes} 分钟` : ""}</span>{(t.musings?.length || t.reflection) && <div className="task-notes">{t.musings?.map(m => <p key={m.id}>碎碎念 {time(m.createdAt)}：{m.text}</p>)}{t.reflection && <p>{t.status === "interrupted" ? "中断说明" : "完成备注"}：{t.reflection}</p>}</div>}</div><b className={t.status === "interrupted" ? "warn" : t.overtimeSeconds > 0 ? "bad" : "good"}>{t.status === "interrupted" ? "中断" : t.overtimeSeconds > 0 ? `超时 ${mins(t.overtimeSeconds)}` : "准时"}</b></article>)}</div>; }
const corgiFrames = {
  sleep: [corgiSleep1, corgiSleep2, corgiSleep3, corgiSleep4],
  play: [corgiPlay1, corgiPlay2, corgiPlay3, corgiPlay4],
  eat: [corgiEat1, corgiEat2, corgiEat3, corgiEat4]
};
function modeFor(r?: DogReward | null, idle?: "sleep" | "toy"): "sleep" | "play" | "eat" { if (r?.animation === "eat" || r?.animation === "sniff" || r?.animation === "care") return "eat"; if (r) return "play"; return idle === "sleep" ? "sleep" : "play"; }
function PixelCorgi(p: { reward?: DogReward | null; idle?: "sleep" | "toy" }) { const m = modeFor(p.reward, p.idle); const [frame, setFrame] = useState(0); useEffect(() => { setFrame(0); const timer = window.setInterval(() => setFrame(v => (v + 1) % corgiFrames[m].length), m === "eat" ? 220 : m === "play" ? 260 : 420); return () => window.clearInterval(timer); }, [m]); return <div className={`pixel-corgi pixel-corgi-${m} ${p.reward ? `pixel-reward-${p.reward.animation}` : ""}`}><img className="pixel-corgi-frame" src={corgiFrames[m][frame]} alt="" draggable={false} />{p.reward && <div className={`dog-treat dog-item-${p.reward.categoryId}`}><i /><span>{p.reward.item}</span></div>}</div>; }
function Completion(p: { note: string; setNote: (v: string) => void; cancel: () => void; confirm: () => void }) { const chips = ["完成得很棒", "很满意", "有点难", "比预期顺利", "需要下次拆小一点", "被打断了", "值得复盘"]; return <div className="dialog-backdrop"><section className="completion-dialog"><div className="section-label">完成备注</div><textarea value={p.note} onChange={e => p.setNote(e.target.value)} placeholder="这项任务完成得怎么样？" autoFocus /><div className="note-chip-list">{chips.map(c => <button key={c} onClick={() => p.setNote(p.note.trim() ? `${p.note.trim()}，${c}` : c)}>{c}</button>)}</div><div className="dialog-actions"><button onClick={p.cancel}>继续编辑</button><button className="primary" onClick={p.confirm}><Check size={17} />确认完成</button></div></section></div>; }
function InterruptDialog(p: { note: string; setNote: (v: string) => void; cancel: () => void; confirm: () => void }) { const chips = ["有别的任务", "累了", "不想做了", "临时开会", "需要等别人反馈", "方向不清楚", "任务太大需要拆分", "状态不适合继续"]; return <div className="dialog-backdrop"><section className="completion-dialog"><div className="section-label">中断理由</div><textarea value={p.note} onChange={e => p.setNote(e.target.value)} placeholder="为什么需要中断这项任务？" autoFocus /><div className="note-chip-list">{chips.map(c => <button key={c} onClick={() => p.setNote(p.note.trim() ? `${p.note.trim()}，${c}` : c)}>{c}</button>)}</div><div className="dialog-actions"><button onClick={p.cancel}>继续计时</button><button className="primary" onClick={p.confirm}>确认中断</button></div></section></div>; }
function DogPanel(p: { dog: DogProfile; reward: DogReward | null; updateDog: (d: DogProfile) => void; categories: TaskCategory[]; settings: AppSettings; saveSettings: (s: AppSettings) => void }) { const [name, setName] = useState(p.dog.name), [gender, setGender] = useState(p.dog.gender); useEffect(() => { setName(p.dog.name); setGender(p.dog.gender); }, [p.dog.name, p.dog.gender]); const age = Math.max(1, Math.floor((Date.now() - new Date(p.dog.birthday).getTime()) / 86400000)); const skill = ["坐下", "握手", "转圈", "等待", "叼球"][p.dog.skillPoints % 5]; const setPref = (id: string, k: DogRewardKind) => p.saveSettings({ ...p.settings, dogRewardPreferences: { ...(p.settings.dogRewardPreferences ?? {}), [id]: k } }); return <section className={`dog-panel ${p.dog.enabled ? "" : "dog-disabled"}`}><div className="dog-header"><div><div className="section-label">柯基伙伴</div><strong>{p.dog.name}</strong><span>{p.dog.gender} · {age < 30 ? `${age} 天` : `${Math.floor(age / 30)} 个月`}</span></div><button onClick={() => p.updateDog({ ...p.dog, enabled: !p.dog.enabled })}>{p.dog.enabled ? "关闭小狗" : "开启小狗"}</button></div><div className="dog-companion-actions"><button className="primary" onClick={() => void window.floatodo.showDogWindow()}>放到桌面上</button><span>专注工作时睡觉，休闲或空闲时玩球，完成任务时触发你设置的奖励。</span></div><PixelCorgi reward={p.reward} /><div className="dog-speech">{p.dog.enabled ? p.reward ? `${p.reward.message}${p.dog.name}${p.reward.action}。` : "我在右下角陪你做事。" : "小狗模式已关闭。"}</div><div className="dog-stats"><DogMeter label="饱腹" value={p.dog.fullness} /><DogMeter label="快乐" value={p.dog.happiness} /><DogMeter label="亲密" value={p.dog.bond} /><DogMeter label="社交" value={p.dog.social} /><DogMeter label="护理" value={p.dog.care} /><div className="dog-skill"><span>技能</span><b>{skill} · Lv.{Math.floor(p.dog.skillPoints / 5) + 1}</b></div></div><div className="dog-settings"><input value={name} onChange={e => setName(e.target.value)} placeholder="小狗名字" /><select value={gender} onChange={e => setGender(e.target.value)}><option value="未设定">未设定</option><option value="妹妹">妹妹</option><option value="弟弟">弟弟</option></select><button onClick={() => p.updateDog({ ...p.dog, name: name.trim() || "Todo", gender: gender.trim() || "未设定" })}>保存资料</button></div><div className="dog-reward-settings"><div className="section-label">完成奖励规则</div>{p.categories.map(c => <label key={c.id}><span><i style={{ background: c.color }} />{c.name}</span><select value={rewardKind(p.settings.dogRewardPreferences, c.id)} onChange={e => setPref(c.id, e.target.value as DogRewardKind)}>{Object.entries(rewardOptions).map(([k, r]) => <option key={k} value={k}>{r.item}</option>)}</select></label>)}</div></section>; }
function DogMeter(p: { label: string; value: number }) { return <div className="dog-meter"><span>{p.label}</span><div><i style={{ width: `${p.value}%` }} /></div><b>{p.value}</b></div>; }
function DogCompanionWindow() { const [reward, setReward] = useState<DogReward | null>(null), [idle, setIdle] = useState<"sleep" | "toy">("toy"), [pinned, setPinned] = useState(true); useEffect(() => { const a = window.floatodo.onDogReward(x => { setReward(x as DogReward); window.setTimeout(() => setReward(null), 5200); }); const b = window.floatodo.onDogState(x => { const i = (x as { idle?: "sleep" | "toy" }).idle; if (i === "sleep" || i === "toy") setIdle(i); }); return () => { a(); b(); }; }, []); const pin = async () => setPinned(await window.floatodo.setDogAlwaysOnTop(!pinned)); return <main className="dog-window"><div className="dog-window-toolbar"><button onClick={pin}>{pinned ? "置顶" : "普通"}</button></div><div className="dog-stage"><PixelCorgi reward={reward} idle={idle} /></div></main>; }
function TuckStripWindow() { const [state, setState] = useState<{ title: string; time: string; overtime: boolean }>({ title: "Floatodo", time: "00:00", overtime: false }); const edge = new URLSearchParams(window.location.search).get("edge") ?? "right"; useEffect(() => window.floatodo.onTuckState(x => { const s = x as Partial<typeof state>; setState({ title: s.title ?? "Floatodo", time: s.time ?? "00:00", overtime: Boolean(s.overtime) }); }), []); const open = () => void window.floatodo.untuckWindow(); return <main className={`tuck-strip-window tuck-strip-${edge}`} onMouseEnter={open} onMouseMove={open} onMouseDown={open}><section className="tucked-timer"><span>{state.title}</span><strong className={state.overtime ? "overtime" : ""}>{state.time}</strong><small>移入展开</small></section></main>; }
function SettingsPanel(p: { settings: AppSettings; saveSettings: (s: AppSettings) => void }) { const [key, setKey] = useState(p.settings.deepseekApiKey), [model, setModel] = useState(p.settings.deepseekModel); useEffect(() => { setKey(p.settings.deepseekApiKey); setModel(p.settings.deepseekModel); }, [p.settings]); return <div className="settings-box"><div className="section-label"><Settings size={17} />DeepSeek 设置</div><input type="password" value={key} onChange={e => setKey(e.target.value)} placeholder="DeepSeek API Key" /><div className="form-row"><input value={model} onChange={e => setModel(e.target.value)} placeholder="模型，例如 deepseek-chat" /><button onClick={() => p.saveSettings({ ...p.settings, deepseekApiKey: key, deepseekModel: model || "deepseek-chat" })}>保存</button></div><button className="plain" onClick={() => void window.floatodo.openDataFolder()}>打开本地数据目录</button></div>; }

const params = new URLSearchParams(window.location.search);
createRoot(document.getElementById("root")!).render(params.get("dogWindow") === "1" ? <DogCompanionWindow /> : params.get("tuckWindow") === "1" ? <TuckStripWindow /> : <App />);
